export const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORIES: "category/SET_CATEGORIES_MAP",
  
  FECTH_SET_CATEGORIES_START: "category/ FECTH_SET_CATEGORIES_START",

  FECTH_SET_CATEGORIES_SUCCESS: "category/ FECTH_SET_CATEGORIES_SUCCESS",

  FECTH_SET_CATEGORIES_FAILED: "category/ FECTH_SET_CATEGORIES_FAILED",
};
